---
title: "distRcpp"
author: "Hsiu J. Ho"
date: "2017年7月10日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

這個套件搜集計算distance matrix的Rcpp, 並進一步套用在RcppParallel以平行計算加強效率. 目前可計算distance如下:
1. Jensen-Shannon distance, 原始碼來源為[Parallel Distance Matrix Calculation with RcppParallel](http://gallery.rcpp.org/articles/parallel-distance-matrix/).
2. Generalized unifrac distance, 參考套件[MiSPU::GUniFrac](https://github.com/cran/MiSPU)的做法.

安裝本套件
```{r,eval=FALSE}
require(devtools)
install_github("hsiujho/distRcpp")
```

**注意**
在CentOS 7 環境下, 安裝會出現錯誤訊息.
```yaml
Error: package or namespace load failed for ‘distRcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 無法載入共享物件 '/home/peter/R/x86_64-redhat-linux-gnu-library/3.4/distRcpp/libs/distRcpp.so' ：
 /home/peter/R/x86_64-redhat-linux-gnu-library/3.4/distRcpp/libs/distRcpp.so: undefined symbol: _ZTIN3tbb4taskE
錯誤: loading failed
停止執行
ERROR: loading failed
```

使用時以`source`指令滙入要用的函數, 如下, 應可執行.
```{r,eval=FALSE}
Rcpp::sourceCpp('./distRcpp/src/jensen_shannon_distance.cpp')
source('./distRcpp/R/JSD.R')
```





