// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GunifracRcpp
NumericMatrix GunifracRcpp(NumericMatrix mat, NumericVector brlen, double powv);
RcppExport SEXP _distRcpp_GunifracRcpp(SEXP matSEXP, SEXP brlenSEXP, SEXP powvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type brlen(brlenSEXP);
    Rcpp::traits::input_parameter< double >::type powv(powvSEXP);
    rcpp_result_gen = Rcpp::wrap(GunifracRcpp(mat, brlen, powv));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_js_distance
NumericMatrix rcpp_parallel_js_distance(NumericMatrix mat);
RcppExport SEXP _distRcpp_rcpp_parallel_js_distance(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_js_distance(mat));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _distRcpp_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distRcpp_GunifracRcpp", (DL_FUNC) &_distRcpp_GunifracRcpp, 3},
    {"_distRcpp_rcpp_parallel_js_distance", (DL_FUNC) &_distRcpp_rcpp_parallel_js_distance, 1},
    {"_distRcpp_rcpp_hello", (DL_FUNC) &_distRcpp_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_distRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
