# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GunifracRcpp <- function(mat, brlen, powv) {
    .Call('_distRcpp_GunifracRcpp', PACKAGE = 'distRcpp', mat, brlen, powv)
}

rcpp_parallel_js_distance <- function(mat) {
    .Call('_distRcpp_rcpp_parallel_js_distance', PACKAGE = 'distRcpp', mat)
}

rcpp_hello <- function() {
    .Call('_distRcpp_rcpp_hello', PACKAGE = 'distRcpp')
}

